on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  schedule:
    - cron: "0 */4 * * *"

jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/checkout@v3
        with:
          repository: "pjx1314/SecuLife"
          fetch-depth: 1
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: "SecuLife"
      - uses: actions/checkout@v3
        with:
          repository: "hoilc/scoop-lemon"
          fetch-depth: 1
          path: "scoop-lemon"
      - uses: actions/checkout@v3
        with:
          repository: "kkzzhizhou/scoop-apps"
          fetch-depth: 1
          path: "scoop-apps"
      - name: Update buckets
        shell: pwsh
        run: |
          .\update.ps1
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git add --all
          if ([string]::IsNullOrEmpty((git status --porcelain))) {
            echo "No changes to commit"
          } else {
            git commit -m "Updated on $(Get-Date -Format "yyyy-MM-dd HH:mm K")"
            git push -f origin master
          }
